name: Update PrivateInternetAccess Data

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download latest lists
        run: bash privateinternetaccess.sh > Readme.md
      
      - name: Force add and commit
        run: |
          git config --local user.email ""
          git config --local user.name "scriptzteam"
          git add -f Readme.md
          git status
          if git status --porcelain | grep -q '^?? \|^A  \|^M  '; then
            echo "Changes detected, committing..."
            git commit -m "Update"
            git push
          else
            echo "No changes to commit"
          fi 
